name: build ci nginx
on:
  push:
    paths:
      - cli/src/test/resources/*
      - deploy/ci.nginx.Dockerfile
jobs:
  build-image:
    name: Build Nginx Image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v2
      - run: cd deploy && ./build-tuf-nginx.sh
      - run: docker push uptane/tuf-nginx:latest
